name: Release Trigger Client

on:
  release:
    types:
      - published

jobs:
  release-trigger-client:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.20.1"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: latest
          args: release --rm-dist